spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=true

spring.datasource.url=jdbc:postgresql://localhost:5432/calorie_dev_db
spring.datasource.username=calorie_dev_user
spring.datasource.password=calorie_dev_password

jwt.secret-key=QE5jUmZValhuMnI1dTh4L0E/RChHK0tiUGRTZ1ZrWXA=